django_error_codes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/', include('error_codes.urls')),
]

error_codes/urls.py
from django.urls import path
from error_codes.docs.views import (DocsTemplateView, CategoriesDocsTemplate,
                                    ErrorDocTemplate, SearchDocTemplate, CodeNotFound)

app_name = 'error'

urlpatterns = [
    path('docs/', DocsTemplateView.as_view(), name='catalog'),
    path('category/<str:name>/', CategoriesDocsTemplate.as_view(), name='error-category'),
    path('code/<str:error_code>/', ErrorDocTemplate.as_view(), name='error-code'),
    path('search', SearchDocTemplate.as_view(), name='search'),
    path('not_found', CodeNotFound.as_view(), name='not-found'),
]

src_error_codes/error_codes/urls.py
from django.urls import path
from error_codes.docs.views import (DocsTemplateView, CategoriesDocsTemplate,
                                    ErrorDocTemplate, SearchDocTemplate)

app_name = 'error'

urlpatterns = [
    path('docs/', DocsTemplateView.as_view(), name='catalog'),
    path('category/<str:name>/', CategoriesDocsTemplate.as_view(), name='error-category'),
    path('code/<str:error_code>/', ErrorDocTemplate.as_view(), name='error-code'),
    path('search', SearchDocTemplate.as_view(), name='search'),
    path('not_found', SearchDocTemplate.as_view(), name='not-found'),

]

src_error_codes/error_codes/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.


class CategoryError(models.Model):

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("error:error-category", kwargs={'name': self.name})

    class Meta:
        ordering = ["-name"]
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Error(models.Model):

    error_code = models.CharField(max_length=80, unique=True)
    message = models.CharField(max_length=250)
    category = models.ForeignKey(CategoryError, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.error_code

    def get_absolut_url(self):
        return reverse("error:error-code", kwargs={'error_code': self.error_code})

    class Meta:
        ordering = ["-error_code"]
        verbose_name = 'Error'
        verbose_name_plural = 'Errors'

src_error_codes/error_codes/docs/views.py
from django.http import JsonResponse
from django.shortcuts import render, reverse
from django.views.generic import TemplateView
from django.views import View
from error_codes.functions import category_all,  get_category_by_name, get_error_code
# Create your views here.


class DocsTemplateView(TemplateView):
    template_name = 'index.html'
    title = 'Rest Error Codes'
    description = 'In this page you can search and see the errors that are handled in this system'

    def get(self, request, *args, **kwargs):
        categories = category_all()
        title = self.title
        description = self.description
        return render(request, self.template_name, locals())


class CategoriesDocsTemplate(View):
    template_name = "details_category.html"

    def get(self, request, name):
        category = get_category_by_name(name)
        errors_codes = category.error_set.all().order_by('error_code')
        return render(request, self.template_name, locals())


class ErrorDocTemplate(View):
    template_name = "details_errors_codes.html"

    def get(self, request, error_code):
        error_code = get_error_code(error_code)
        return render(request, self.template_name, locals())


class SearchDocTemplate(View):

    def get(self, request):
        param_error_code = request.GET.get('value', '')
        error_code = get_error_code(param_error_code)
        if not error_code:
            url = reverse('error:not-found')
            return JsonResponse({'url': url}, safe=False)
        url = reverse('error:error-code', kwargs={'error_code': error_code})
        return JsonResponse({'url': url}, safe=False)


class CodeNotFound(TemplateView):
    template_name = 'not_found.html'

src_error_codes/error_codes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'boostrap/styles.css' %}" rel="stylesheet" crossorigin="anonymous">
    <title>Catalog Errors</title>
</head>
<body>
{% include 'search.html' %}
<div class="container mt-1">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="{% static 'boostrap/bundle.js' %}"></script>
{% block js %}
{% endblock js %}
</html>

src_error_codes/error_codes/templates/details_category.html
{% extends 'base.html' %}

{% block content %}
<p class="fs-3">{{ category.name|title }}</p>
    <div class="container">
        <p>List of category error codes: {{ category.name|title }}</p>
        <ul class="list-group">
            {% for error_code in errors_codes %}
                <li class="list-group-item list-group-item-action"><strong class="fs-3">{{ error_code.error_code }}</strong>
                <p>{{ error_code.description|truncatechars:100 }}</p>
                    <a href="{{ error_code.get_absolut_url }}">Ver más</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock%}

src_error_codes/error_codes/templates/details_errors_codes.html
{% extends 'base.html' %}

{% block content %}

<p class="fs-2" id="title">{{ error_code.error_code|title }}</p>
    <p>
        {{ error_code.description }}
    </p>

{% endblock %}
{% block js %}
    <script>

function load() {
    document.getElementById('title').innerText = document.getElementById('title').innerText.toUpperCase()
}
    window.onload = load;
    </script>
{% endblock js %}

src_error_codes/error_codes/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row align-items-start">
        <div class="list-group mt-5 col-3">
            <p>List of all categories registered</p>
            {% for category in categories %}
                <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category.name|title }}</a>
            {% endfor %}
        </div>
      <div class="col m-5 col-6">
        <h2>{{title}}</h2>
        <p>{{description}}</p>
      </div>
    </div>
    </div>

{% endblock %}

src_error_codes/error_codes/templates/not_found.html
{% extends 'base.html' %}

{% block content %}
    <h1>Not found</h1>
{% endblock %}

src_error_codes/error_codes/templates/search.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Rest Errors</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'error:catalog' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Contact</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">GitHub</a>
        </li>
      </ul>
      <form class="d-flex" id="form-search">
        <input id="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button id="btn-search" class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block js %}
    <script>

    let form_search = document.getElementById('form-search')
    let btn_search = document.getElementById('btn-search')
    let search = document.getElementById('search')

    btn_search.addEventListener('click', async function (e){
        e.preventDefault()
      const response = await fetch(`{% url 'error:search' %}?value=${search.value} `, {
          'method':'GET'
      })
        .then( response => response.json() )
        .then( response => {
            window.location.href = response.url
        } );

    })

    </script>
{% endblock %}